public class Constants {
  public static final String ERROR_LEGAL_AGE_FOR_FLIGHT = 'You are less than the legal age for flying';
  public static final String ERROR_SHIP_DEPARTED = 'The ship has already departed';
  public static final String FLIGHT_STATUS_DECLINED = 'Declined';
  public static final String SEND_FINAL_EMAIL = 'polashkind@gmail.com';
  public static final String API_KEY = '581730305a4742bf84ddf52c4b781c05';
  public static final String FUZZY_NAME = 'fuzzyname';
  public static final String AGE = 'age';
  ublic static final String STATUS_CODE = '200';
}